### ISSUE TITLE
Scrapy project

### ISSUE THREAD

**Issue by nirgn975** [nirgn975/open-pension-crawler#1]
Create a new [scrapy](https://scrapy.org/) project (that don't do anything for now, just the files).

**Comment by nirgn975** [comment]
@daniellevi1 There wasn't a `master` branch - strange.
I created one. But I couldn't merge them because git history things. Please `checkout` to `master` and create a branch from there, and create the files again in that new branch.

After you do that, you could open a PR and if you finish assign it to me.
Then I'll open more issues.

The main purpose of this scrapy crawler is to crawl the pensions websites and download the data files automatically. We'll start with one of the pensions and then move on (the first will be hard, but after the first it'll be fine). I Don't know yet with which one we'll start but I hope I'll know by the evening .

**Comment by daniellevi1** [comment]
@nirgn975 I deleted my local project and clone again.
After that I had just master branch. I checkout to new branch 1 and then created scrap framework. 
When I'm trying to push the branch, i got that error - 

"To https://github.com/nirgn975/open_pension_scraper.git
 ! [rejected]        1 -> 1 (non-fast-forward)
error: failed to push some refs to 'https://github.com/nirgn975/open_pension_scraper.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details."

When I'm trying to pull after that, it says that "There is no tracking information for the current branch."
What should i do?

**Comment by nirgn975** [comment]
@daniellevi1 Try again now (I deleted the `1` branch from `origin`).

**Comment by daniellevi1** [comment]
@nirgn975 After some problems it worked, thanks.
I opened PR.
In the pensions websites there are mostly CSV or XLS files?
Where to store the data, in PostgreSQL db?
Do we need to parse the data before storing it or after?

**Comment by nirgn975** [comment]
@daniellevi1 **I see a branch but I don't see any PR**.
I'm pretty sure you'll download only `xls` files from the pensions websites.
You don't need to store them on anything right now, and not parse them (the parsing is the script Roy write).

You'll write the crawler and to find the `xls` files you'll need to parse the pension website, the html.  
I send an email to Ophir to tell us with which of the pension to begin with and to send some examples. I'll add him to this Repo so we can ask him questions.

**Comment by nirgn975** [comment]
Here is how they name the `xls` files:
https://github.com/nirgn975/open_pension_scraper/wiki

**Comment by daniellevi1** [comment]
@nirgn975 I think the pattern Unordered, beacuase that example '511234567_b111_0315.xlsx'
doesn't match the pattern.

**Comment by nirgn975** [comment]
@daniellevi1 Yeah I pretty sure he confused the order, I'll edit the photo.

**Comment by daniellevi1** [comment]
@nirgn975 I think it should be
xxxxxxxxx_Tnum_qqyy.xlsx

**Comment by nirgn975** [comment]
@daniellevi1 Yep. I Edit the image, see the wiki again.
