### ISSUE TITLE
Missalinices

### ISSUE THREAD

**Issue by nirgn975** [nirgn975/open-pension-crawler#13]
Now that we have a requirements file, you should edit the Installation section in the `README.md` file, like:
```md
1. pip install -r requirements.txt
```

And lets add a `LICENSE` file with the text:
```
Copyright (c) 2016

Permission to use, copy, modify, and/or distribute this software for
any purpose with or without fee is hereby granted, provided that the
above copyright notice and this permission notice appear in all
copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
```

It's a `ISC` license so let's add a badge that tells people in a glance the project license.
You can look at [this](https://github.com/nirgn975/Elmctron) project, take the `svg` badge from there, but the link should be to our `LICENSE` file of course.
Add the license badge at the `README.md` file before the `travis` badge.

**Comment by daniellevi1** [comment]
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Counting objects: 108, done.
Compressing objects: 100% (64/64), done.
Writing objects: 100% (108/108), 15.76 KiB | 0 bytes/s, done.
Total 108 (delta 43), reused 99 (delta 40)
remote: Resolving deltas: 100% (43/43), done.
To git@github.com:nirgn975/open_pension_scraper.git
- [new branch]      4 -> 4

**Comment by nirgn975** [comment]
@daniellevi1 You forgot to open the PR..
